services:
  - type: web
    name: sports-betting-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        fromDatabase:
          name: sports-betting-db
          property: connectionString
    healthCheckPath: /health
